### ISSUE TITLE
Conversion of PPT to PDF drops images

### ISSUE THREAD

**Issue by groe** [ojwb/lloconv#3]
Hi!

I am converting several office files to PDF and noticed the following behaviour: While conversion of PPTX-files works perfectly fine, converting PPT-files to PDF removes all images.

See this screenshot:
![lloconv-issue](https://cloud.githubusercontent.com/assets/515293/5681208/ad883866-9816-11e4-9dad-279fca872591.png)

I am using LibreOffice 4.3.4.1 with the latest lloconv version (pulled from git today).

Any idea on what could be the reason for this or how it could be fixed?

**Comment by ojwb** [comment]
I tested with LibreOffice 4.4.0 beta 1 and I do get images when converting a couple of PPT files to PDF.

I don't have 4.3.x installed on this machine, but if that doesn't handle it, there's not much lloconv can do - it's really just a thin command line wrapper around the "LibreOfficeKit" API, and it's the latter which does all the hard work.

4.4.0 isn't released yet, but RC2 is now available, so I'd suggest trying that:

http://www.libreoffice.org/download/libreoffice-fresh/?version=4.4.0

**Comment by groe** [comment]
Thank you, Olly! I will have a look at 4.4.0!

**Comment by ojwb** [comment]
Closing - it works for me with 4.4.0, and if it doesn't with older versions, there unfortunately isn't much we can do about it.
