### ISSUE TITLE
documentLoad from array

### ISSUE THREAD

**Issue by vertrex** [ojwb/lloconv#4]
Hi, 

Does LibreOfficeKit had a function that permit to load a document from an array rather than a file path (documentLoad equivalent taking a char* for example) , also I would like to get the converted document back as an array (rather than using saveAs). 
Do you have some pointer for documentation about LibreOfficeKit ? I could write the wrapper if necessary.

Also, do you think that the code is portable on Windows ?  (if the right symbols are exported I think I just need to rewrite the library loading part to use LoadLibrary)

Thanks.

**Comment by ojwb** [comment]
> Does LibreOfficeKit had a function that permit to load a document from an array rather than a file path (documentLoad equivalent taking a char* for example) , also I would like to get the converted document back as an array (rather than using saveAs).

No, the API currently only supports reading a file (or URL) and writing a file (I think essentially does "File->Open.." and "File->Save As...").

> Do you have some pointer for documentation about LibreOfficeKit ? I could write the wrapper if necessary.

The documentation unfortunately seems rather thin - I just figured it out from the headers, with a little help from some of the LO developers.

> Also, do you think that the code is portable on Windows ? (if the right symbols are exported I think I just need to rewrite the library loading part to use LoadLibrary)

No idea I'm afraid.  I'd see if there's an equivalent DLL and poke it to see what symbols there are.

Not an issue in lloconv, so closing.

**Comment by ojwb** [comment]
The latest code in LibreOfficeKit seems to have support for other platforms (but still can only load from and save to files/URLs).

It also looks like this code is now actually packaged, so we can probably stop bundling it, but for now I've just updated the in-tree copy.

I've only tested on Linux, but feel free to give it a go.

**Comment by vertrex** [comment]
Thanks, for the reply I looked at the code and chat a bit on #libreoffice-dev . FinallyI used UNO and it work well but it's certainly a bit slower. Sorry to have open an issue for that but I didn't find an other way to 'chat' on github.
