### ISSUE TITLE
Known values for "-o OPTIONS"

### ISSUE THREAD

**Issue by pcdinh** [ojwb/lloconv#8]
Hi,

Where can I find list of values for "-o"? For now, "SkipImages" is mentioned. What options should I use if I want to embed images into HTML or export images into separate files and link them to the exported HTML document?

Thanks

**Comment by ojwb** [comment]
We just pass the options to the LibreOfficeKit API so it's up to LibreOffice what's supported there - unfortunately they don't seem to provide a full list anywhere.  https://github.com/LibreOffice/online/blob/master/bundled/include/LibreOfficeKit/LibreOfficeKit.hxx#L50 is the nearest thing there seems to be to documentation:

```
     * @param pFilterOptions options for the export filter, e.g. SkipImages.
     *        Another useful FilterOption is "TakeOwnership".  It is consumed
     *        by the saveAs() itself, and when provided, the document identity
     *        changes to the provided pUrl - meaning that '.uno:ModifiedStatus'
     *        is triggered as with the "Save As..." in the UI.
     *        "TakeOwnership" mode must not be used when saving to PNG or PDF.
```

So there's also `TakeOwnership`, but that doesn't sound like it's going to be useful with lloconv.  It sounds like there may at least be other options specific to particular filters, but you'd have to dig into the LO code, or ask them.

If you do find other options which are useful for lloconv, I'd be happy to take a patch to document them.
